(load "book\p216-constraint-propagate.scm")
; 3.34-3.35
(define (squarer a b)
  (define (process-new-value)
	(if (has-value? b)
	  (if (< (get-value b) 0)
		(error "square less than 0 -- SQUARE" (get-value b))
		(set-value! a (sqrt (get-value b)) me))
	  (set-value! b (* a a) me)))
  (define (process-forget-value)
	(forget-value! a me)
	(forget-value! b me)
	(process-new-value))
  (define (me request)
	(cond ((eq? request 'I-have-a-value)
		   (process-new-value))
		  ((eq? request 'I-lost-my-value)
		   (process-forget-value))
		  (else
			(error "unknow request -- squarer" request))))
  (connect a me)
  (connect b me)
  me)
